apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sam-sample-service-3-root
  title: Sample Service 3 - Sam
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: sblausten
  lifecycle: experimental